version: '3.8'
services:
  dev_page_analyzer:
    image: postgres:latest
    container_name: dev_page_analyzer
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    restart: always